### PR TITLE
Lower _ and Bb dependencies to match Mn

### PR DESCRIPTION
**Pull request by paulfalgout**
And it works.  Why not?

### CODE REVIEW

**Comment by paulfalgout** [comment]
by the way to test this I locally:

```
npm i underscore@1.4.4
npm i backbone@1.0.0
gulp
```

ran fine, but I didn't try anything else..  but if it works there I'm assuming it'd be fine all the way up.

**Comment by jamiebuilds** [comment]
Could you add this to the testing matrix the way Marionette has it?

**Comment by paulfalgout** [comment]
Yep sure thing.

**Comment by paulfalgout** [comment]
Man that matrix is huge now.  That's what is shipping with `2.4.2`  But it seems unnecessarily overkill.
I could make it more like https://github.com/marionettejs/backbone.radio/blob/master/.travis.yml#L6 and pick a few for node 0.10, 0.12 and io?

**Comment by jamiebuilds** [comment]
Yeah, I think we only need to test this for the latest io.js and the version of Backbone doesn't really matter.

**Comment by paulfalgout** [comment]
Ok so on top of specifying the node version in the matrix,  I've pulled out some of the variations.  Basically the various underscores and lodashes are there, and I switched up the Bb's for those because why not.. as well as throwing in some 0.10 for good measure.  But it's mainly testing 0.12 and an io.js

**Comment by jamiebuilds** [comment]
Cool

**Pull request merged**
